apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.movieService.pvc.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: default
spec:
  accessModes:
    - {{ .Values.movieService.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.movieService.pvc.storage }}
  storageClassName: {{ .Values.movieService.pvc.storageClassName }}
