apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.castService.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.castService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.castService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.castService.name }}
    spec:
      containers:
      - name: {{ .Values.castService.name }}
        image: {{ .Values.castService.image.repository }}:{{ .Values.castService.image.tag }}
        command: {{ .Values.castService.command }}
        args: ["app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: {{ .Values.castService.port }}
        env:
        - name: DATABASE_URI
          value: {{ .Values.castService.databaseUri }}
        volumeMounts:
        - name: {{ .Values.castService.volume.name }}
          mountPath: {{ .Values.castService.volume.mountPath }}
      volumes:
      - name: {{ .Values.castService.volume.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.castService.volume.claimName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.castService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.castService.name }}
  ports:
  - port: {{ .Values.castService.port }}
    targetPort: {{ .Values.castService.port }}