apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.movieDb.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.movieDb.name }}
  replicas: {{ .Values.movieDb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.movieDb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.movieDb.name }}
    spec:
      containers:
      - name: {{ .Values.movieDb.name }}
        image: {{ .Values.movieDb.image.repository }}:{{ .Values.movieDb.image.tag }}
        ports:
        - containerPort: {{ .Values.movieDb.port }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.movieDb.postgresUser }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.movieDb.secretName }}
              key: {{ .Values.movieDb.secretKey }}
        - name: POSTGRES_DB
          value: {{ .Values.movieDb.postgresDb }}
        volumeMounts:
        - name: {{ .Values.movieDb.volume.name }}
          mountPath: {{ .Values.movieDb.volume.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.movieDb.volume.name }}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.movieDb.volume.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.movieDb.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.movieDb.name }}
  ports:
  - port: {{ .Values.movieDb.port }}