apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  MOVIE_DB_URI: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
  CAST_DB_URI: postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev
  CAST_SERVICE_HOST_URL: http://cast-service:8000/api/v1/casts/