apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-service-claim0
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path