# templates/nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-exam.fullname" . }}-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "helm-exam.name" . }}
      component: nginx
  template:
    metadata:
      labels:
        app: {{ include "helm-exam.name" . }}
        component: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "helm-exam.fullname" . }}-nginx-config
            items:
              - key: default.conf
                path: default.conf
